package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "base",
    hdrs = [
        "integral_types.h",
        "int128.h",
        "macros.h",
        "mutex.h",
        "port.h",
        "stringprintf.h",
        "template_util.h"
    ],
    srcs = [
        "stringprintf.cc"
    ],
)
