cc_library(
    name = "base",
    hdrs = [
        ":macros.h",
        ":integral_types.h",
        ":port.h",
        ":stringprintf.h"
    ],
    srcs = [
        ":stringprintf.cc"
    ],
    visibility = ["//visibility:public"],
)
